# Generated by Django 5.0.6 on 2026-10-02 03:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaConocimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp automático al crear el registro', verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp automático al modificar el registro', verbose_name='Fecha de actualización')),
                ('is_deleted', models.BooleanField(default=False, help_text='Marca si el registro fue eliminado (soft delete)', verbose_name='Eliminado lógicamente')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp cuando se realizó el soft delete', null=True, verbose_name='Fecha de eliminación')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del área')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Slug URL')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('icono', models.CharField(blank=True, default='🐾', help_text='Emoji representativo (ej: 🎯 🐾 😺 🏃)', max_length=50, verbose_name='Icono/Emoji')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden de visualización')),
                ('activa', models.BooleanField(default=True, verbose_name='Área activa')),
            ],
            options={
                'verbose_name': 'Área de Conocimiento',
                'verbose_name_plural': 'Áreas de Conocimiento',
                'ordering': ['orden', 'nombre'],
                'indexes': [models.Index(fields=['activa', 'orden'], name='academico_a_activa_e5af91_idx')],
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp automático al crear el registro', verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp automático al modificar el registro', verbose_name='Fecha de actualización')),
                ('is_deleted', models.BooleanField(default=False, help_text='Marca si el registro fue eliminado (soft delete)', verbose_name='Eliminado lógicamente')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp cuando se realizó el soft delete', null=True, verbose_name='Fecha de eliminación')),
                ('codigo', models.CharField(help_text='Código único tipo FLF-001, FLF-002...', max_length=20, unique=True, verbose_name='Código del curso')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del curso')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='Slug URL')),
                ('descripcion', models.TextField(verbose_name='Descripción completa')),
                ('resumen', models.CharField(max_length=300, verbose_name='Resumen corto (catálogo)')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='cursos/', verbose_name='Imagen del curso')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador (no visible en catálogo)'), ('PUBLICADO', 'Publicado (visible y matriculable)'), ('ARCHIVADO', 'Archivado (no disponible)')], default='BORRADOR', help_text='CHOICES explícito - REQUERIDO POR PAUTA', max_length=20, verbose_name='Estado del curso')),
                ('modalidad', models.CharField(choices=[('PRESENCIAL', 'Presencial (en el territorio)'), ('VIRTUAL', 'Virtual (videollamada gatuna)'), ('HIBRIDO', 'Híbrido (mixto)')], default='PRESENCIAL', max_length=20, verbose_name='Modalidad')),
                ('fecha_inicio', models.DateTimeField(verbose_name='Fecha y hora de inicio')),
                ('fecha_fin', models.DateTimeField(verbose_name='Fecha y hora de fin')),
                ('fecha_limite_inscripcion', models.DateTimeField(help_text='Después de esta fecha no se permite matricularse', verbose_name='Fecha límite de inscripción')),
                ('cupos_maximos', models.PositiveIntegerField(help_text='Número máximo de estudiantes por cohorte', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)], verbose_name='Cupos máximos')),
                ('cupos_disponibles', models.PositiveIntegerField(default=0, help_text='Se actualiza automáticamente al matricular/cancelar', verbose_name='Cupos disponibles')),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio de matrícula (CLP)')),
                ('activo', models.BooleanField(default=True, verbose_name='Curso activo')),
                ('destacado', models.BooleanField(default=False, verbose_name='Destacado en home')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cursos', to='academico.areaconocimiento', verbose_name='Área de conocimiento')),
            ],
            options={
                'verbose_name': 'Curso/Bootcamp',
                'verbose_name_plural': 'Cursos/Bootcamps',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
