# Generated by Django 5.0.6 on 2026-10-02 03:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='coordinador',
            field=models.ForeignKey(limit_choices_to={'rol': 'COORDINADOR'}, on_delete=django.db.models.deletion.PROTECT, related_name='cursos_coordinados', to=settings.AUTH_USER_MODEL, verbose_name='Coordinador responsable'),
        ),
        migrations.AddField(
            model_name='curso',
            name='prerequisitos',
            field=models.ManyToManyField(blank=True, help_text='Cursos que deben completarse antes', to='academico.curso', verbose_name='Prerrequisitos'),
        ),
        migrations.AddIndex(
            model_name='curso',
            index=models.Index(fields=['estado', 'activo', 'fecha_inicio'], name='academico_c_estado_9c40e0_idx'),
        ),
        migrations.AddIndex(
            model_name='curso',
            index=models.Index(fields=['area', 'estado'], name='academico_c_area_id_794880_idx'),
        ),
        migrations.AddIndex(
            model_name='curso',
            index=models.Index(fields=['fecha_inicio'], name='academico_c_fecha_i_c624b1_idx'),
        ),
    ]
