# Generated by Django 5.0.6 on 2026-10-02 03:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarroMatricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp automático al crear el registro', verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp automático al modificar el registro', verbose_name='Fecha de actualización')),
                ('activo', models.BooleanField(default=True, help_text='Solo un carro activo por estudiante', verbose_name='Carro activo')),
            ],
            options={
                'verbose_name': 'Carro de Matrícula',
                'verbose_name_plural': 'Carros de Matrícula',
            },
        ),
        migrations.CreateModel(
            name='ItemCarro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp automático al crear el registro', verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp automático al modificar el registro', verbose_name='Fecha de actualización')),
                ('precio_congelado', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio congelado')),
                ('nombre_congelado', models.CharField(max_length=200, verbose_name='Nombre congelado')),
                ('codigo_congelado', models.CharField(max_length=20, verbose_name='Código congelado')),
            ],
            options={
                'verbose_name': 'Item del Carro',
                'verbose_name_plural': 'Items del Carro',
            },
        ),
        migrations.CreateModel(
            name='MatriculaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp automático al crear el registro', verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp automático al modificar el registro', verbose_name='Fecha de actualización')),
                ('precio_pagado', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio pagado')),
                ('nombre_curso', models.CharField(max_length=200, verbose_name='Nombre del curso')),
                ('codigo_curso', models.CharField(max_length=20, verbose_name='Código del curso')),
                ('codigo_matricula', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Código de matrícula (UUID)')),
                ('activa', models.BooleanField(default=True, verbose_name='Matrícula activa')),
                ('fecha_inicio_curso', models.DateTimeField(verbose_name='Fecha inicio del curso')),
                ('fecha_fin_curso', models.DateTimeField(verbose_name='Fecha fin del curso')),
            ],
            options={
                'verbose_name': 'Matrícula Oficial',
                'verbose_name_plural': 'Matrículas Oficiales',
            },
        ),
        migrations.CreateModel(
            name='OrdenMatricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp automático al crear el registro', verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp automático al modificar el registro', verbose_name='Fecha de actualización')),
                ('is_deleted', models.BooleanField(default=False, help_text='Marca si el registro fue eliminado (soft delete)', verbose_name='Eliminado lógicamente')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp cuando se realizó el soft delete', null=True, verbose_name='Fecha de eliminación')),
                ('numero_orden', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Número de orden')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de pago'), ('PAGADO', 'Pagado - Matrículas generadas'), ('ENTREGADO', 'Entregado/Completado (curso finalizado)'), ('CANCELADO', 'Cancelado (cupos liberados)')], default='PENDIENTE', help_text='CHOICES explícito - Control transaccional de inventario/cupos', max_length=20, verbose_name='Estado de la orden')),
                ('estudiante_nombre', models.CharField(max_length=300, verbose_name='Nombre estudiante')),
                ('estudiante_email', models.EmailField(max_length=254, verbose_name='Email estudiante')),
                ('estudiante_username', models.CharField(max_length=150, verbose_name='Username estudiante')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Subtotal')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total')),
                ('fecha_pago', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de pago')),
                ('fecha_cancelacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cancelación')),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de entrega/completado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('metodo_pago', models.CharField(blank=True, max_length=50, verbose_name='Método de pago simulado')),
            ],
            options={
                'verbose_name': 'Orden de Matrícula',
                'verbose_name_plural': 'Órdenes de Matrícula',
                'ordering': ['-created_at'],
            },
        ),
    ]
