# Generated by Django 5.0.6 on 2026-10-02 03:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0002_initial'),
        ('matriculas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='carromatricula',
            name='estudiante',
            field=models.OneToOneField(limit_choices_to={'rol': 'ESTUDIANTE'}, on_delete=django.db.models.deletion.CASCADE, related_name='carro_matricula', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante'),
        ),
        migrations.AddField(
            model_name='itemcarro',
            name='carro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='matriculas.carromatricula', verbose_name='Carro'),
        ),
        migrations.AddField(
            model_name='itemcarro',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_carro', to='academico.curso', verbose_name='Curso'),
        ),
        migrations.AddField(
            model_name='matriculadetalle',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='academico.curso', verbose_name='Curso'),
        ),
        migrations.AddField(
            model_name='ordenmatricula',
            name='estudiante',
            field=models.ForeignKey(limit_choices_to={'rol': 'ESTUDIANTE'}, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante'),
        ),
        migrations.AddField(
            model_name='matriculadetalle',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='matriculas.ordenmatricula', verbose_name='Orden'),
        ),
        migrations.AddIndex(
            model_name='carromatricula',
            index=models.Index(fields=['estudiante', 'activo'], name='matriculas__estudia_640d3e_idx'),
        ),
        migrations.AddIndex(
            model_name='itemcarro',
            index=models.Index(fields=['carro', 'curso'], name='matriculas__carro_i_8f89b6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='itemcarro',
            unique_together={('carro', 'curso')},
        ),
        migrations.AddIndex(
            model_name='ordenmatricula',
            index=models.Index(fields=['estudiante', 'estado'], name='matriculas__estudia_c6abf0_idx'),
        ),
        migrations.AddIndex(
            model_name='ordenmatricula',
            index=models.Index(fields=['estado', 'created_at'], name='matriculas__estado_eb0a90_idx'),
        ),
        migrations.AddIndex(
            model_name='ordenmatricula',
            index=models.Index(fields=['numero_orden'], name='matriculas__numero__7f8ab1_idx'),
        ),
        migrations.AddIndex(
            model_name='matriculadetalle',
            index=models.Index(fields=['orden', 'activa'], name='matriculas__orden_i_1be8e2_idx'),
        ),
        migrations.AddIndex(
            model_name='matriculadetalle',
            index=models.Index(fields=['codigo_matricula'], name='matriculas__codigo__184b9d_idx'),
        ),
        migrations.AddIndex(
            model_name='matriculadetalle',
            index=models.Index(fields=['curso', 'activa'], name='matriculas__curso_i_12759a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='matriculadetalle',
            unique_together={('orden', 'curso')},
        ),
    ]
